### ISSUE TITLE
Version String

### ISSUE THREAD

**Issue by PhoenixCodingStuff** [UltraCosmetics/UltraCosmetics#108]
### Describe the feature and how it would be used

The version present on SpigotMC is 
![image](https://github.com/datatags/UltraCosmetics/assets/97077949/30a4a9bc-c6f6-4c5c-b6de-794f82600695)
but the version in the plugin jar is 3.2.1**-RELEASE**
hence it triggers false updates on people using SpigotMC API
![image](https://github.com/datatags/UltraCosmetics/assets/97077949/c7a0306e-ef7e-439e-8a11-a335a471731a)

My suggestion is to match the version in plugin jar to the same as the SpigotMC page

### Are there alternatives?

No

### Additional information

N/A

**Comment by datatags** [comment]
Let me check which versions of UC this will break, since some expect only numbers and dots in the version number

**Comment by datatags** [comment]
Oh, I thought that's what you were saying initially. I guess it could be changed in the jar if there was a separate field so UC knows if it's a release or dev build of some kind, I'd have to look at how to do that.

**Comment by datatags** [comment]
So I'm not sure this was a good solution, because that puts `3.0-DEV-b1` and `3.0-RELEASE` as the same version, when in fact they are very different. This also prevents bStats from differentiating between dev builds and releases. What are you using to detect available updates?

I may go back to adding `-RELEASE` to the Spigot release number, again depending on how much that would break
